# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='course_id',
        ),
        migrations.AddField(
            model_name='description',
            name='course',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
            preserve_default=False,
        ),
    ]
